name: CI

on:
  - push
  - pull_request

env:
  NOKOGIRI_USE_SYSTEM_LIBRARIES: true
  JAVA_OPTS=-Djava.security.egd: file:/dev/urandom
  WD_CACHE_TIME: 0

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - 2.7
          - '3.0'
          - 3.1
#          - head
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
#      - name: Set up a lua script
#        if:
#        run: |-
#          mkdir -p ~/.config/awesome;
#          echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua;
#          awesome &
#      - name: Set up selenium
#        if:
      - name: test
        run: bundle exec rake travis

#  rubocop:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Set up Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 3.1
#          bundler-cache: true
#      - name: rubocop
#        run: bundle exec rubocop
